DalgoT4D/dbt_shofco

- models/staging/wash/staging_water_production.sql
> fixed small sheet change

- models/marts/gender/life_skills_training_participants.sql
- models/marts/gender/life_skills_training_sessions.sql
- models/staging/gender/staging_champions.sql
- models/staging/gender/staging_life_skills_training_participant_details.sql
- models/staging/gender/staging_life_skills_training_session_details.sql
SHOFCO requested filter changes due to added columns.
Pipeline fixes because of schema changes.
> pipeline + filter fixes acc to shofco request

- macros/extract_case_table_from_sl_commcare_json.sql
- models/marts/sl/sl_service_completion_follow_up_analytics.sql
- models/source.yml
- models/staging/sl/staging_sl_service_completion_follow_up.sql
Target issue is CREATED NEW SL MODEL 
> Added sl service completion follow up

- models/marts/sl/sl_new_analytics.sql
- models/staging/sl/staging_sl_new.sql
Target issue is Added sl_new  
> added sl new

- .gitignore
- models/source.yml
- models/staging/sl/staging_service_enrollment.sql
> worked on service enrollment staging model

- models/source.yml
- models/staging/sl/staging_nita.sql
> Nita status

- models/source.yml
- models/staging/sl/staging_dignity_kit_issuance.sql
> initial commit for dignity kit issuance

- models/source.yml
- models/staging/sl/staging_co_working_first_visit.sql
> updated sources file and created co working staging model

- models/source.yml
- models/staging/sl/staging_upskilling_form.sql
> Upskilling form

- models/source.yml
- models/staging/sl/staging_sl_business_grants_assessment.sql
Target issue is grants assesment added 
> grants assesment

- models/source.yml
- models/staging/sl/staging_sl_business_grants_issuance.sql
Target issue is added business grants issuance data 
> added business grants issuance data

- models/marts/sl/service_completion_followup.sql
> added production model for service completion followup

- models/marts/sl/placement_followup.sql
- models/staging/sl/staging_sl_placement_followup.sql
Target issue is Added placement followup marts
> Added placement followup marts

- models/marts/sl/service_enrollment.sql
> created service enrollment marts model

- models/source.yml
- models/staging/sl/staging_swep_exhibition_sales.sql
> added swep exhibition and sales staging model

- models/marts/sl/business_grants_issuance.sql
> created business grants issuance marts

- models/marts/gender/case_occurence_pii.sql
- models/marts/sl/coworking_individual_profiles.sql
- models/marts/sl/coworking_visit_log.sql
- models/marts/sl/upskilling.sql
- models/source.yml
- models/staging/sl/staging_co_working_first_visit.sql
- models/staging/sl/staging_co_working_return_visit.sql
- models/staging/sl/staging_upskilling_completion.sql
- models/staging/sl/staging_upskilling_form.sql
> added and fixed sl models

- models/marts/sl/daycare_assessment.sql
- models/marts/sl/dignity_assessment.sql
- models/marts/sl/service_enrollment.sql
- models/staging/sl/staging_co_working_first_visit.sql
- models/staging/sl/staging_co_working_return_visit.sql
- models/staging/sl/staging_service_enrollment.sql
- models/staging/sl/staging_sl_placement_followup.sql
- models/staging/sl/staging_swep_exhibition_sales.sql
- models/staging/sl/staging_swep_production.sql
- models/staging/sl/staging_upskilling_completion.sql
- models/staging/sl/staging_upskilling_form.sql
> more sl changes

- models/marts/sl/service_enrollment.sql
- models/staging/sl/staging_service_enrollment.sql
Target issue is I have updated location on service enrolment
> updated location on service enrolment

- models/marts/sl/business_grants_issuance.sql
- models/staging/sl/staging_sl_business_grants_issuance.sql
Target issue is updated staging_sl_business_grants_issuance
> updated staging_sl_business_grants_issuance

- models/staging/sl/staging_sl_placement_followup.sql
Target issue is final_updated_location_on_placement_followup
> final_updated_location_on_placement_followup

- models/marts/gender/case_occurence.sql
- models/marts/gender/case_occurence_pii.sql
- models/staging/gender/staging_gender_survivors_commcare.sql
- models/staging/gender/survivors_data.sql
> changed logic for county and ward matching
